Logger
waterloo-rocketry/cansw_processor_stm pull request #25
Opened 2024-06-17 02:31 UTC by celery6

minor adjustments to hopefully increase certainty that logger won't overflow any buffers or get stuck.
- give back logwritemutex before exiting logGeneric (I thought josh fixed this already but I couldn't find that change?)
- get rid of counting the log header string separately from the log msg. It's all under MAX_MSG_LENGTH now for simplicity and less confusing/potentially incorrect logic.
- change fullBuffersQueue to length NUM_LOG_BUFFERS instead of `NUM_LOG_BUFFERS - 1`. reasoning described in comment
- replace stupid source enums with source strings

2024-06-17 03:23 UTC, celery6 commented
testing code:
- enabled controller, log, flightphase tasks.
- Added log calls in controller and flightphase. 
- Added uart print in log task. 

Verify that the logs are in fact printing

![image](https://github.com/waterloo-rocketry/cansw_processor_stm/assets/71736183/51c21953-4ec5-4313-9ae6-d9564a421973)

2024-06-19 03:03 UTC, Joe-Joe-Joe-Joe commented
Nice
I can probably find time to test this in person tmr

2024-06-27 22:06 UTC, Lucifersan approved these changes
works great other than the bits of code i had to remove
idk if its great practice to like approve after i just committed smth but it does seem to be working!
it still does the thing that it did in the last line of christine's ss where it gets halfway through a message and then it just cuts off with "[other message]", I'm not sure if thats what this is trying to resolve? Given how christine didn't really flag that I'm assuming not but I will not merge this for now for that reason
it is logging tho and otits runs and passes and controler absolutely spams messages and also its mispelled

2024-06-27 23:55 UTC, Lucifersan requested changes
nvm lol the formatting is actually maybe an issue do not merge till that is fixed

2024-06-28 03:58 UTC, celery6 commented
@Lucifersan just realized the test print uses uart_transmit not printf_ so this does actually print the entire buffer together.

This issue is actually just the hal_uart_transmit timeout of 500 ticks being too low since unsurprisingly it takes longer than 0.5s to transmit a book-length novel of logs :skull: 

increased timeout to 3000 and it works as expected. (log buffer itself is actually fine.) we can ignore this issue

2024-06-28 03:59 UTC, celery6 commented
ill clean up the testing code then this should be good to merge!

2024-06-28 04:22 UTC, celery6 commented
removed testing code, also cleaned up commits. lgtm?

2024-06-28 19:19 UTC, Lucifersan approved these changes
does not lgtmwtf i didnt see that

2024-06-28 19:28 UTC, Lucifersan commented
mommy what.
im gonna change that and test it lmao
<img width="530" alt="Screenshot 2024-06-28 at 3 28 17 PM" src="https://github.com/waterloo-rocketry/cansw_processor_stm/assets/35873939/0d3edfe8-efd4-4ac2-b12a-46f10cb112cc">

2024-06-28 19:40 UTC, celery6 commented
wtf I literally built and it built how tf 😭😭

2024-06-28 21:51 UTC, merged