Comp sim
waterloo-rocketry/cansw_processor_stm pull request #77
Opened 2024-07-26 17:31 UTC by Joe-Joe-Joe-Joe

- Cleaned up old commented-out code
- Modified controller logic to only run the controller in coast phase of flight (prevents windup)
- Modified daemon task priority so that freeRTOS functions can actually run from ISRs
- Added a couple more logs in places

2024-07-26 17:32 UTC, Joe-Joe-Joe-Joe commented on STM32Cube/Core/Src/main.c
> +#if  defined(TEST_MODE) && defined(DEBUG)
Stops us from accidentally running otits in prod (though its also a define so I guess it should never run in prod config anyway) :face:

2024-07-26 17:40 UTC, Joe-Joe-Joe-Joe commented on STM32Cube/Tasks/state_estimation.c
> +			if(build_state_est_data_msg(millis_(), &euler.angle.roll, STATE_FILTER_ROLL, &msg)) xQueueSend(busQueue, &msg, 10);
this somehow got reverted on master?

2024-07-26 22:01 UTC, celery6 requested changes

2024-07-26 23:34 UTC, Joe-Joe-Joe-Joe commented on STM32Cube/Tasks/controller.c
> +			printf_("extension: %f\n", extension);
okay but why
the whole point is that it gets compiled out in prod

2024-07-26 23:43 UTC, celery6 commented on STM32Cube/Tasks/controller.c
> +			printf_("extension: %f\n", extension);
does it get compiled out??? there's a ifdef around putchar but nothing guarding the actual printf which is annoyingly large computing sink

2024-07-27 00:14 UTC, Joe-Joe-Joe-Joe commented on STM32Cube/Tasks/controller.c
> +			printf_("extension: %f\n", extension);
ah okay I will comment them out for now and we can revisit after tomorrow

2024-07-27 01:25 UTC, celery6 approved these changes

2024-07-27 02:16 UTC, merged