Implement basic logging functionality
waterloo-rocketry/cansw_processor_stm pull request #9
Opened 2024-04-18 17:00 UTC by celery6

some notes
- only 1 log function can run at once, so logging is blocking up to 50 ticks (arbitrary number for now)
  - logs can be printed out of order cuz tasks are unblocked by priority not time. however the timestamp is acquired before waiting, so actual order can be post-processed if needed
- still needs more thinking about full buffer edge cases for protecting against out of bounds and overwriting !!!!!!!! Are there any glaring issues currently?
- since the logger function uses snprintf, all tasks that log will get stack eaten by snprintf :( should do better stack usage analysis someday to make sure this is fine...
- not sure if each buffer itself should be protected by a mutex or if the isFull flag is enough. I think using per-buffer mutexes would still require the isFull flag due to the handoff between log funcs and dump queue (something needs to guard a full buffer while its waiting to be dumped). idk

2024-04-22 17:15 UTC, Joe-Joe-Joe-Joe commented
Have you tested on the hardware yet?

2024-04-23 11:08 UTC, Joe-Joe-Joe-Joe requested changes
See comments. Also test the code if that hasn't already been done. Design wise I'm very happy with it for now. Stuff like efficiency improvements on the UART is not necessary for now, but quickly will be once we want to run threads at any reasonable speed (no 1 second timeouts lol).

2024-04-23 11:08 UTC, Joe-Joe-Joe-Joe commented on STM32Cube/Tasks/log.c
> +            // TODO: do uart transmit better (use _IT?)
*Use DMA

2024-04-23 19:35 UTC, celery6 commented
Tested latest changes, works well. Tested spamming logs in all tasks and buffers don't get full with the current osDelay(1000), but they do get full with shorter osDelays. To be optimized later ig!

merged master but didn't initialize task in main.

2024-04-23 19:40 UTC, celery6 commented
Yes

2024-04-23 19:49 UTC, Joe-Joe-Joe-Joe commented
try bumping baud rate to 500000
I know for a fact the chip supports it, idk if the programmer will bottleneck us there tho

2024-04-24 11:45 UTC, Joe-Joe-Joe-Joe approved these changes

2024-04-28 00:29 UTC, merged